In [1]:
import numpy as np 

arr = np.arange (0,20,2)
arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [2]:
arr_flot = np.random.rand(4,3)
arr_flot

array([[0.8058378 , 0.88399699, 0.83179254],
       [0.13803152, 0.6137671 , 0.50567553],
       [0.85087886, 0.18062995, 0.1317192 ],
       [0.77464909, 0.14601951, 0.54467892]])

In [3]:
arr_ent = np.random.randint(10, size=(2,3))
arr_ent

array([[0, 3, 6],
       [7, 3, 7]])

In [4]:
arr_6 = np.full((3,3),6) #EquipoKND
arr_6

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [5]:
np.append(arr,[12,13,14,51])

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 12, 13, 14, 51])

In [6]:
np.insert(arr,2, [42,34])

array([ 0,  2, 42, 34,  4,  6,  8, 10, 12, 14, 16, 18])

In [7]:
np.delete(arr_ent,1,axis=0)

array([[0, 3, 6]])