In [1]:
import numpy as np 

a = np.array([2,4,9],float)

In [2]:
a

array([2., 4., 9.])

In [3]:
np.sqrt(a)

array([1.41421356, 2.        , 3.        ])

In [4]:
np.exp(a)

array([7.38905610e+00, 5.45981500e+01, 8.10308393e+03])

In [5]:
np.log(a)

array([0.69314718, 1.38629436, 2.19722458])

In [6]:
np.sin(a)

array([ 0.90929743, -0.7568025 ,  0.41211849])

In [7]:
np.cos(a)

array([-0.41614684, -0.65364362, -0.91113026])

In [8]:
np.mean(a)

5.0

In [9]:
np.std(a)

2.943920288775949

In [10]:
np.var(a)

8.666666666666666