In [1]:
import numpy as np 

arr_ent = np.random.randint(100,size=(3,4))
arr_ent

array([[75, 56, 18, 50],
       [49, 41, 28, 37],
       [72,  9, 51, 26]])

In [2]:
arr_ent.astype(float) #EquipoKND

array([[75., 56., 18., 50.],
       [49., 41., 28., 37.],
       [72.,  9., 51., 26.]])

In [3]:
arr_ent

array([[75, 56, 18, 50],
       [49, 41, 28, 37],
       [72,  9, 51, 26]])

In [4]:
arr_ent.sort()
arr_ent

array([[18, 50, 56, 75],
       [28, 37, 41, 49],
       [ 9, 26, 51, 72]])

In [5]:
arr_ent.sort(axis=0)
arr_ent

array([[ 9, 26, 41, 49],
       [18, 37, 51, 72],
       [28, 50, 56, 75]])

In [6]:
arr_ent

array([[ 9, 26, 41, 49],
       [18, 37, 51, 72],
       [28, 50, 56, 75]])

In [7]:
arr_ent = arr_ent.reshape(4,3) #EquipoKND
arr_ent

array([[ 9, 26, 41],
       [49, 18, 37],
       [51, 72, 28],
       [50, 56, 75]])

In [8]:
plano_arr = arr_ent.flatten()

print(arr_ent)
print(plano_arr)

[[ 9 26 41]
 [49 18 37]
 [51 72 28]
 [50 56 75]]
[ 9 26 41 49 18 37 51 72 28 50 56 75]


In [9]:
lista_arr = plano_arr.tolist()
lista_arr

[9, 26, 41, 49, 18, 37, 51, 72, 28, 50, 56, 75]

In [10]:
arrays= np.split(arr_ent,4)
arrays

[array([[ 9, 26, 41]]),
 array([[49, 18, 37]]),
 array([[51, 72, 28]]),
 array([[50, 56, 75]])]

In [11]:
np.concatenate((arrays[1],arrays[0]),axis=0)

array([[49, 18, 37],
       [ 9, 26, 41]])

In [12]:
arr_ent

array([[ 9, 26, 41],
       [49, 18, 37],
       [51, 72, 28],
       [50, 56, 75]])

In [13]:
t_arr = arr_ent.T
t_arr

array([[ 9, 49, 51, 50],
       [26, 18, 72, 56],
       [41, 37, 28, 75]])